# Generated by Django 5.2.8 on 2025-11-11 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_author_user_borrower_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
        migrations.RemoveField(
            model_name='borrower',
            name='user',
        ),
    ]
